.TH "friendcrypt::FriendCryptException" 3 "Thu May 5 2016" "Version 0.5.2" "FriendCrypt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
friendcrypt::FriendCryptException \- The \fBFriendCryptException\fP class Exception for FriendCrypt\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fcexception\&.h>\fP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFriendCryptException\fP (int what)"
.br
.ti -1c
.RI "\fBFriendCryptException\fP (const \fBFriendCryptException\fP &other)"
.br
.ti -1c
.RI "\fBFriendCryptException\fP (\fBFriendCryptException\fP &&other)=delete"
.br
.ti -1c
.RI "\fBFriendCryptException\fP & \fBoperator=\fP (const \fBFriendCryptException\fP &)=delete"
.br
.ti -1c
.RI "\fBFriendCryptException\fP & \fBoperator=\fP (\fBFriendCryptException\fP &&other)=delete"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBFriendCryptException\fP &lhs, const \fBFriendCryptException\fP &rhs)"
.br
.RI "\fIoperator == You can verify two exception with if \fP"
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBFriendCryptException\fP &lhs, const \fBFriendCryptException\fP &rhs)"
.br
.RI "\fIoperator != You can verify two exception with if \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBFriendCryptException\fP class Exception for FriendCrypt\&. 
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator!= (const \fBFriendCryptException\fP & lhs, const \fBFriendCryptException\fP & rhs)\fC [friend]\fP"

.PP
operator != You can verify two exception with if 
.PP
\fBParameters:\fP
.RS 4
\fIlhs\fP left 
.br
\fIrhs\fP right 
.RE
.PP
\fBReturns:\fP
.RS 4
false if equal 
.RE
.PP

.SS "bool operator== (const \fBFriendCryptException\fP & lhs, const \fBFriendCryptException\fP & rhs)\fC [friend]\fP"

.PP
operator == You can verify two exception with if 
.PP
\fBParameters:\fP
.RS 4
\fIlhs\fP left 
.br
\fIrhs\fP right 
.RE
.PP
\fBReturns:\fP
.RS 4
true if equal 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for FriendCrypt from the source code\&.
