.TH "friendcrypt::CWKData" 3 "Thu May 5 2016" "Version 0.5.2" "FriendCrypt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
friendcrypt::CWKData \- The \fBCWKData\fP class Object creator: \fBCryptWithKeccak\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fccrypt\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBsetData\fP (uint8_t *data, long len)"
.br
.RI "\fIsetData Set crypted data or plaintext (copy) (This will rewrite in inside buffer if you use encode/decode) \fP"
.ti -1c
.RI "bool \fBsetPass\fP (uint8_t *pass, long len)"
.br
.RI "\fIsetPass (copy) \fP"
.ti -1c
.RI "bool \fBsetSalt\fP (uint8_t *salt, long len)"
.br
.RI "\fIsetSalt (copy) \fP"
.ti -1c
.RI "bool \fBgetData\fP (uint8_t *data)"
.br
.RI "\fIgetData (copy, crypted data length and plaintext length is equals) \fP"
.ti -1c
.RI "long \fBgetDataLen\fP ()"
.br
.RI "\fIgetDataLen \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const long \fBkBlockSize\fP"
.br
.RI "\fIkBlockSize Actual block size \fP"
.ti -1c
.RI "const int \fBkMinLen\fP = 16"
.br
.RI "\fIkMinLen Minimum reguest length \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCryptWithKeccak\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBCWKData\fP class Object creator: \fBCryptWithKeccak\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool friendcrypt::CWKData::getData (uint8_t * data)"

.PP
getData (copy, crypted data length and plaintext length is equals) 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true if data is copied 
.RE
.PP

.SS "long friendcrypt::CWKData::getDataLen ()"

.PP
getDataLen 
.PP
\fBReturns:\fP
.RS 4
data length 
.RE
.PP

.SS "bool friendcrypt::CWKData::setData (uint8_t * data, long len)"

.PP
setData Set crypted data or plaintext (copy) (This will rewrite in inside buffer if you use encode/decode) 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP crypted data or plaintext 
.br
\fIlen\fP length 
.RE
.PP
\fBReturns:\fP
.RS 4
true if data is copied 
.RE
.PP

.SS "bool friendcrypt::CWKData::setPass (uint8_t * pass, long len)"

.PP
setPass (copy) 
.PP
\fBParameters:\fP
.RS 4
\fIpass\fP password 
.br
\fIlen\fP length (no more than Block Size, min: kMinLen) 
.RE
.PP
\fBReturns:\fP
.RS 4
true if pass is copied 
.RE
.PP

.SS "bool friendcrypt::CWKData::setSalt (uint8_t * salt, long len)"

.PP
setSalt (copy) 
.PP
\fBParameters:\fP
.RS 4
\fIsalt\fP 
.br
\fIlen\fP length (no more than Block Size, min: kMinLen) 
.RE
.PP
\fBReturns:\fP
.RS 4
true if salt is copied 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for FriendCrypt from the source code\&.
